version: '3'
services:
    backend:
        environment:
            - TAG
        image: 'titincocom/titin-backend-chat-bot:${TAG}'
        env_file:
            - ../.env
        volumes:
            - '/usr/src/app/node_modules'
        logging:
            driver: awslogs
            options:
                awslogs-region: us-east-2
                awslogs-group: /microservice/titin-pro-backend-chat-bot
                awslogs-create-group: 'true'
                tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}-{{.ID}}'
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    memory: 256M
